/** Minden felhasználónak látható magyar szöveg. .tsx-ben nincs string-literál. */

export const copy = {
  app: {
    name: 'Családi Fuvarszervező',
    tagline: 'Kézi fuvaregyeztetés egy helyen',
  },

  nav: {
    today: 'Ma',
    week: 'Hét',
    rides: 'Fuvarok',
    events: 'Programok',
    schedule: 'Órarend',
    more: 'Egyéb',
    settings: 'Beállítások',
  },

  login: {
    email: 'Email',
    password: 'Jelszó',
    submit: 'Bejelentkezés',
    submitting: 'Bejelentkezés…',
    failed: 'Bejelentkezés sikertelen',
  },

  common: {
    save: 'Mentés',
    saving: 'Mentés…',
    cancel: 'Mégsem',
    close: 'Bezárás',
    back: 'Vissza',
    add: 'Hozzáad',
    delete: 'Törlés',
    edit: 'Módosítás',
    loading: 'Betöltés…',
    today: 'Ma',
    error: 'Hiba',
    errorOccurred: 'Hiba történt',
    retry: 'Újra',
    done: 'Kész',
    create: 'Létrehozás',
    person: 'Személy',
    personRequired: 'Személy *',
    unknown: '?',
    dash: '—',
    working: '…',
    new: 'Új',
    yesDelete: 'Igen, törlöm',
    none: 'Egyik sem',
    everyone: 'Mindenki',
    pick: '– válassz –',
    from: 'Tól *',
    to: 'Ig *',
    reason: 'Ok',
    home: 'Otthon',
    members: 'Tagok',
    history: 'Előzmények',
    minutesShort: (n: number) => `${n} p`,
    minutes: (n: number) => `${n} perc`,
  },

  role: {
    parent: 'Szülő',
    grandparent: 'Nagyszülő',
    child: 'Gyerek',
    babysitter: 'Felügyelet',
  },

  form: {
    programName: 'Program neve',
    programNameRequired: 'Program neve *',
    date: 'Dátum',
    who: 'Kinek',
    whoRequired: 'Kinek *',
    start: 'Kezdés',
    end: 'Vége',
    location: 'Helyszín',
    locationRequired: 'Helyszín *',
    transport: 'Szállítás',
    child: 'Gyerek',
    group: 'Csoport',
    pick: 'Válassz…',
    pickChild: 'Válassz gyereket…',
    pickGroup: 'Válassz csoportot…',
    notSet: 'Nincs megadva',
    placeholderProgram: 'pl. Zeneiskola',
    customAddress: 'Egyszeri cím (felülírja a helyszín nevét)',
    note: 'Megjegyzés',
    until: (date: string) => `ig: ${date}`,
  },

  a11y: {
    settings: 'Beállítások',
    messages: 'Üzenetek',
    prevWeek: 'Előző hét',
    nextWeek: 'Következő hét',
    close: 'Bezárás',
    merge: 'Összevonás',
    gridView: 'Rácsnézet',
    listView: 'Listanézet',
    addEvent: 'Új program',
    illness: 'Betegség rögzítése',
    moreActions: 'További műveletek',
    delete: 'Törlés',
    edit: 'Szerkesztés',
  },

  direction: {
    viszi: 'Viszi',
    begyujti: 'Begyűjti',
  },

  status: {
    cancelled: 'Elmarad',
    cancelledWithReason: (reason: string) => `Elmarad — ${reason}`,
    noDriver: 'Nincs sofőr',
    self: 'Önállóan',
    selfGoes: 'Önállóan megy',
    selfGoesHome: 'Önállóan megy haza',
    youDrive: 'Te vezetsz',
    comingAlong: 'te is mész',
    modified: 'Módosított',
    locationMissing: 'Hol?',
    tight: 'szűkös',
    tightGap: (mins: number) => `${mins} perc a következőig — szűkös`,
    tightBang: (mins: number) => `${mins} perc — szűkös`,
    gapMins: (mins: number) => `${mins} perc`,
  },

  sentence: {
    viszi: (driver: string, childAcc: string) => `${driver} viszi ${childAcc}`,
    begyujti: (driver: string, childAcc: string) => `${driver} begyűjti ${childAcc}`,
    visziWithCompanion: (driver: string, companion: string) => `${driver} viszi, ${companion} is megy`,
    youAlsoGo: (driver: string) => `${driver} viszi, te is mész`,
    youCollect: 'Te gyűjtöd be',
    bothWays: (driver: string) => `${driver} viszi és begyűjti`,
    groupAssignedInbound: (driver: string, who: string) => `${driver} begyűjti ${who}`,
    groupAssignedOutbound: (driver: string, who: string) => `${driver} elviszi ${who}`,
    groupOpenInbound: (who: string) => `Ki gyűjti be ${who}?`,
    groupOpenOutbound: (who: string) => `Ki viszi el ${who}?`,
    othersToday: (names: string, n: number) =>
      `${names} ${n} fuvart visz ma`,
  },

  ma: {
    title: 'Ma',
    yourDay: 'A te napod',
    othersToday: 'A többiek ma',
    openRides: 'Nincs sofőr',
    calendarOk: (time: string) => `Naptár naprakész · ${time}`,
    openCount: (n: number) =>
      n === 1 ? 'Egy fuvarra nincs sofőr' : `${n} fuvarra nincs sofőr`,
    noRidesYours: 'Ma nincsenek fuvaraid',
    illness: 'Beteg',
    illnessTitle: 'Betegség / szünet rögzítése',
  },

  rides: {
    title: 'Fuvarok',
    filterAll: 'Mind',
    filterMine: 'Enyém',
    whoDrives: 'Válassz sofőrt',
    whoElse: 'Ki megy még?',
    whoDrivesGrouped: 'Válassz sofőrt',
    driving: 'Vezet',
    with: 'Vele',
    selfTransport: 'Önállóan',
    leaveOpen: 'Nincs sofőr',
    conflict: 'ütközés',
    calendar: 'Naptár',
    absence: 'Szünet',
    returnAlso: 'Be is gyűjti',
    transitAlso: 'A kapcsolódó fuvart is ő vigye',
    transitHint: (time: string, title: string) =>
      `Ugyanazzal a sofőrrel továbbmehet: ${time} · ${title}`,
    transfer: 'Továbbmehet',
    grouped: 'Egy autóval',
    groupedCount: (n: number) => `${n} megálló`,
    split: 'Inkább külön vigyék',
    mergeTitle: 'Összevonás',
    mergeHint: 'Válassz ki legalább 2 fuvart az összevonáshoz',
    mergeExit: 'Kilépés az összevonásból',
    mergeStart: 'Fuvarok összevonása',
    merging: 'Összevonás…',
    mergeSelected: (n: number) => `Összevon (${n} kijelölve)`,
    mergeN: (n: number) => `Összevon (${n} fuvar)`,
    aloneOk: 'Egyedül megy',
    readyCount: (n: number) => `Kész (${n} fő)`,
    maxCompanions: (driver: string) => `(max 2 · ${driver} vezet)`,
    allAssigned: 'Minden fuvarnak van sofőrje',
    openThisWeek: (n: number) =>
      n === 1 ? 'Egy fuvarra nincs sofőr ezen a héten' : `${n} fuvarra nincs sofőr ezen a héten`,
    emptyMine: 'Neked nincs fuvarod ezen a héten',
    emptyAll: 'Nincs fuvar ezen a héten',
    travelMins: (n: number) => `~${n} perc`,
    pickDriver: 'Válassz sofőrt',
    swap: 'Csere',
  },

  week: {
    title: 'Hét',
    emptyTitle: 'Ezen a héten nincs program',
    emptySub: 'Tanítási szünet van?',
    noDriver: 'nincs sofőr',
    person: 'Személy',
    editCancel: 'Módosítás / Lemondás',
    dropHere: 'Ide',
    dropHereHint: 'Ide húzva',
  },

  events: {
    title: 'Programok',
    subtitle: 'Egyszeri programok',
    emptyTitle: 'Még nincs heti program',
    emptyOneOff: 'Nincs egyszeri program',
    emptySub: 'Vedd fel, ami csak ezen a napon van.',
    add: 'Új program',
    edit: 'Program szerkesztése',
    addSubmit: 'Program hozzáadása',
    saveEdit: 'Módosítás mentése',
    cancelEvent: 'Program elmarad',
    outbound: 'Viszi',
    inbound: 'Begyűjti',
    editBadge: 'Szerkeszt',
  },

  schedule: {
    title: 'Órarend',
    subtitle: 'Ismétlődő programok',
    emptyTitle: 'Még nincs heti program',
    emptySub: 'Vedd fel, ami minden héten ugyanúgy van.',
    generate: 'Órarend frissítése',
    generating: 'Fut…',
    generateHint: 'Az órarendből létrehozza a következő 30 nap programjait és fuvarjait',
    generateDone: (n: number) => `Kész: ${n} program a következő 30 napra`,
    generateError: (msg: string) => `Hiba: ${msg}`,
    editRow: 'Órarend szerkesztése',
    newRow: 'Új órarend-sor',
    addRow: 'Órarend hozzáadása',
    deleteRow: 'Órarend törlése',
    day: 'Nap',
    days: 'Nap(ok)',
    outbound: 'Viszi',
    inbound: 'Begyűjti',
    pickChild: 'Válassz gyereket!',
    pickGroup: 'Válassz csoportot!',
    fillRequired: 'Töltsd ki a kötelező mezőket!',
    timeOrder: 'A befejezési időnek a kezdési idő után kell lennie!',
    pickDay: 'Válassz legalább egy napot!',
    weekdaysMonFri: 'H–P',
    createNDays: (n: number) => `${n} napra hoz létre sort`,
    noGroups: 'Még nincs csoport. Hozz létre egyet a Beállítások → Csoportok fülön.',
    validFrom: 'Érvényes-től',
    validTo: 'Érvényes-ig (üres=örök)',
  },

  settings: {
    title: 'Beállítások',
    appearance: 'Megjelenítés',
    hideCancelled: 'Elmaradt programok elrejtése',
    hideCancelledHint: 'A Hét és a Fuvarok nézetben nem jelenik meg az Elmarad',
    push: 'Push értesítések',
    pushHint: 'Értesítés sofőr-hozzárendeléskor',
    tabs: {
      locations: 'Helyszínek',
      travel: 'Útidő',
      available: 'Elérhetőség',
      unavailable: 'Nem elérhető',
      calendars: 'Naptárak',
      groups: 'Csoportok',
      absences: 'Szünetek',
      message: 'Üzenet',
      diagnose: 'Diagnózis',
    },
    name: 'Név',
    nameRequired: 'Név *',
    address: 'Cím (opcionális)',
    homeCannotDelete: 'Az otthon helyszín nem törölhető',
    confirmDeleteLocation: 'Biztosan törlöd ezt a helyszínt?',
    confirmDeleteRoute: 'Törlöd ezt az útvonalat?',
    minutesPlaceholder: 'Percek',
    invalidMinutes: 'Érvényes percszámot adj meg',
    noteOptional: 'Megjegyzés (opcionális)',
    groupNameRequired: 'A csoport nevét kötelező megadni!',
    groupMinMembers: 'Legalább 2 tagot adj hozzá!',
    groupEdit: 'Csoport szerkesztése',
    groupNew: 'Új csoport',
    groupName: 'Csoport neve *',
    groupHint: 'Fuvar-csoportok: egyszerre több személyt lehet hozzárendelni egy fuvarhoz.',
    groupEmpty: 'Még nincs csoport. Hozz létre egyet!',
    breakFields: 'Töltsd ki az összes kötelező mezőt (személy, dátum)',
    breakOrder: 'A kezdő dátum nem lehet nagyobb a végdátumnál',
    breakSaved: (n: number) => `Szünet mentve — ${n} program elmarad`,
    breakDeleted: (n: number) => `Szünet törölve — ${n} program visszaállítva`,
    confirmDeleteBreak: 'Töröljük a szünetet? A törölt szünet miatt elmaradt programok visszakerülnek tervezettbe.',
    breakDelete: 'Szünet törlése',
    breakHint: 'Szünet megadásával az adott személy összes programja elmarad a megjelölt napokra. Törléskor az órarend szerinti programok visszakerülnek tervezettbe.',
    breakAdd: 'Új szünet hozzáadása',
    breakNew: 'Új szünet-időszak',
    breakEmpty: 'Még nincs rögzített szünet-időszak.',
    breakNotePlaceholder: 'pl. téli szünet, influenza…',
    reasonIllness: 'Betegség',
    reasonVacation: 'Szünet',
    reasonVacationLong: 'Szünet / vakáció',
    reasonOther: 'Egyéb',
    googleOk: 'Google Calendar sikeresen csatlakoztatva!',
    googleFail: 'Google Calendar csatlakoztatás nem sikerült.',
    googleSynced: 'Szinkronizálva!',
    googleDisconnected: 'Google Calendar lecsatlakoztatva.',
    confirmDisconnectGoogle: (name: string) => `Lecsatlakoztatod ${name} Google Naptárát?`,
    googleHint: 'Szülők csatlakoztatják saját Google-fiókjukat. A hozzárendelt fuvarok automatikusan megjelennek a Google Calendarban, a Google-eseményeket pedig ütközésvizsgálatra használjuk.',
    googleConnect: 'Csatlakoztatás',
    googleDisconnect: 'Lecsatlakoztatás',
    googleSync: 'Szinkron',
    googleNotConnected: 'Nincs csatlakoztatva',
    otherCalendars: 'Egyéb naptárak',
    locationsHint: 'Az utazási idő mátrix alapjai. Az otthon jelölés kötelező a fuvarszámításhoz.',
    tbdLocation: 'Helyszín nincs megadva',
    tbdLabel: 'Helyszín később',
    isHome: 'Ez az otthon',
    newLocation: 'Új helyszín',
    travelHint: 'Kézzel felvett menetidők percben. Kattints a percszámra a szerkesztéshez.',
    travelFrom: 'Honnan',
    travelTo: 'Hová',
    travelMins: 'Perc',
    travelEmpty: 'Még nincs menetidő megadva.',
    newRoute: 'Új útvonal',
    travelFromPick: 'Honnan…',
    travelToPick: 'Hová…',
    availHint: 'Mikor tud vezetni az adott sofőr. Figyelmeztető — nem tiltja a beosztást.',
    noDrivers: 'Nincs sofőr a háztartásban.',
    unavailHint: 'Mikor nem elérhető az adott személy. Minden más időpont szabad. Figyelmeztető — nem tiltja a beosztást automatikusan.',
    noPersons: 'Nincs személy a háztartásban.',
    pushPlaceholder: 'pl. Változás a mai napon',
    pushBody: 'Részletek…',
    pushSend: 'Push küldése',
    pushSending: 'Küldés…',
    pushSent: (sent: number, failed?: number) =>
      `Elküldve ${sent} eszközre${failed ? ` (${failed} hiba)` : ''}`,
    pushError: (msg: string) => `Hiba: ${msg}`,
    pushCustomHint: 'Küldj egyedi push értesítést a háztartás tagjainak.',
    pushTitleLabel: 'Cím *',
    pushBodyLabel: 'Szöveg (opcionális)',
    pushWho: 'Küldés kinek',
    pushEmptyLogs: 'Még nem volt küldés.',
    sentToDevices: (n: number) => `${n} eszközre küldve`,
    pushLogSent: (sent: number, target: number) => `${sent}/${target} küldve`,
    pushLogDelivered: (n: number) => `${n} megérkezett`,
    pushLogOpened: (n: number) => `${n} megnyitva`,
    diagnoseRun: 'Diagnózis futtatása',
    diagnoseRunning: 'Ellenőrzés…',
    diagnoseFix: 'Javítás',
    diagnoseFixError: (msg: string) => `Javítási hiba: ${msg}`,
    diagnoseFetchError: (msg: string) => `Lekérési hiba: ${msg}`,
    diagnoseHint: 'Ellenőrzi az adatok egyezését: fuvarok, időtartamok, órarend-átfedések, útidők.',
    diagnose: {
      noHome: 'Nincs otthoni helyszín',
      homeOk: (name: string) => `Otthoni helyszín: ${name}`,
      ridesOk: 'Minden tervezett programnak van fuvarja',
      ridesMissing: (n: number) => `${n} tervezett program fuvar nélkül`,
      dirsOk: 'A fuvarirányok teljesek (viszi / begyűjti)',
      dirsIncomplete: (n: number) => `${n} program hiányos fuvariránnyal`,
      cancelledOk: 'Elmaradt programokhoz nincs fuvar',
      cancelledHasRides: (n: number) => `${n} elmaradt programnak még van fuvarja`,
      driversOk: 'Minden fuvarnak van sofőrje',
      driversMissing: (n: number) => `${n} fuvar sofőr nélkül`,
      orphanOk: 'Minden fuvar programhoz tartozik',
      orphanRides: (n: number) => `${n} fuvar nem kapcsolódik programhoz`,
      overlapOk: 'Az órarend dátumok nem fedik át egymást',
      overlap: (n: number) => `${n} órarend dátum-átfedés (azonos személy + hét napja)`,
      travelOk: 'Minden órarend-helyszínhez van útidő (oda+vissza)',
      travelMissing: (routes: string) => `Hiányzó útidők: ${routes}`,
      timesOk: 'Minden program időtartama helyes',
      timesBad: (n: number) => `${n} program hibás időtartammal`,
      summaryOk: (occs: number, rides: number, rows: number) =>
        `Minden ellenőrzés sikeres (${occs} program, ${rides} fuvar, ${rows} órarend-sor)`,
      summaryIssues: (err: number, warn: number, occs: number, rides: number) =>
        `${err} hiba · ${warn} figyelmeztetés (${occs} program, ${rides} fuvar)`,
      item: (date: string, title: string) => `${date} ${title}`,
      homeTo: (name: string) => `Otthon→${name}`,
      toHome: (name: string) => `${name}→Otthon`,
    },
    signOut: 'Kijelentkezés',
  },

  inbox: {
    title: 'Értesítések',
    empty: 'Nincs új értesítés',
    emptySub: 'Még nincs értesítés',
    sentTo: (n: number) => `${n} eszközre küldve`,
  },

  offline: {
    banner: 'Offline — a változtatások mentve, küldés ha van net',
    back: 'Újra online — szinkronizálva',
    pending: (n: number) => `(${n} várakozó bejegyzés)`,
  },

  empty: {
    todayYours: { title: 'Ma nincs fuvarod', sub: 'Szabad napod van.' },
    todayNone: { title: 'Ma nincs program', sub: 'Senkinek nincs fuvarja.' },
    todayClaim: { title: 'Nincs mit vállalni', sub: 'Minden mai fuvarnak van sofőrje.' },
    week: { title: 'Ezen a héten nincs program', sub: 'Tanítási szünet van?' },
    weekSitter: { title: 'Nincs fuvarod ezen a héten', sub: 'Csak azok a programok látszanak, amikhez fuvarod van.' },
    rides: { title: 'Minden fuvarnak van sofőrje', sub: 'Ezen a héten nincs több teendőd.' },
    ridesFilter: { title: 'Ebben a szűrőben nincs fuvar', sub: 'Mutasd mindet' },
    schedule: { title: 'Még nincs heti program', sub: 'Vedd fel, ami minden héten ugyanúgy van.' },
    absences: { title: 'Nincs aktív szünet', sub: 'Mindenki jól van.' },
    inbox: { title: 'Nincs új értesítés', sub: '' },
    error: { title: 'Nem sikerült betölteni', sub: 'Újra' },
  },

  breakModal: {
    illnessTitle: 'Betegség rögzítése',
    absenceTitle: 'Szünet / kiesés',
    who: 'Személy',
    reason: 'Ok',
    from: 'Mettől',
    to: 'Meddig',
    note: 'Megjegyzés (opcionális)',
    notePlaceholder: 'pl. láz, osztálykirándulás…',
    submit: 'Lemondom a programokat',
  },

  quickLog: {
    title: 'Gyors rögzítés',
    cancelLabel: 'Elmarad',
    cancelDesc: 'Program(ok) lemondása',
    noteLabel: 'Megjegyzés',
    noteDesc: 'Rögzítés részletek nélkül',
    pickProgram: 'Válassz ki egy programot.',
    pickAtLeastOne: 'Jelölj ki legalább egy programot.',
    writeNote: 'Írj be egy megjegyzést.',
    notePlaceholder: 'Megjegyzés *…',
    cancelPlaceholder: 'Ok / megjegyzés (opcionális)…',
    cancelledOne: 'Program lemondva',
    cancelledN: (n: number) => `${n} program lemondva`,
    noteSaved: 'Megjegyzés rögzítve',
    noPrograms: (name: string) => `Nincs aktív program ma — ${name}`,
    noProgramsGeneric: 'Nincs aktív program ma.',
    cancelSubmit: (n: number) => n > 1 ? `${n} program lemondása` : 'Program lemondása',
    noteSubmit: 'Megjegyzés rögzítése',
  },

  override: {
    thisOnly: 'Csak ezen a napon',
    fromNow: 'Mostantól minden héten',
    templateWarn: 'Az órarend módosul — az összes jövőbeli alkalom az új adatokat kapja.',
    confirmThis: (date: string) => `Biztosan lemondod a ${date} napi programot?`,
    confirmFuture: (date: string) => `Biztosan lemondod ${date} napjától az összes jövőbeli programot?`,
    cancelAction: 'Lemondás',
    locationPlaceholder: 'pl. Keleti pályaudvar, 2. kijárat',
    notePlaceholder: 'pl. rövidebb nap, más bejárat…',
    resetSchedule: 'Visszaállítás az eredeti órarendre',
  },

  weekday: {
    long: ['Hétfő', 'Kedd', 'Szerda', 'Csütörtök', 'Péntek', 'Szombat', 'Vasárnap'] as const,
    short: ['H', 'K', 'Sze', 'Cs', 'P', 'Szo', 'V'] as const,
    mid: ['Hétf', 'Kedd', 'Szer', 'Csüt', 'Pént', 'Szom', 'Vasá'] as const,
  },

  and: 'és',
} as const

export type Copy = typeof copy
